/**
 * Content Conversion (dry run) — what story and challenge rewards become in currency.
 *
 * Under the currency design (stat-currency-progression.md §7), authored content
 * stops granting stat points and pays currency instead: `statChanges` on story
 * outcomes and `statBoosts` on challenge rewards become `currency`. This walks
 * the real data, converts every positive grant through each stat's recipe at
 * the calibrated income scale (the rule careerSim already pays story income
 * by), and prints a Markdown report to review before anything is rewritten.
 * It changes no data.
 *
 * Penalties (negative stat changes) are listed separately: with no stat
 * respec there is no currency to take back, so what they become is a design
 * question, not a conversion.
 *
 * Run: npx tsx src/test/analysis/contentConversion.ts > docs/proposals/content-conversion-dry-run.md
 * Env: INCOME_SCALE=1.2
 */

import type { StatName } from '../../types';
import { StoryEventRepository } from '../../data/storyEvents';
import { CHALLENGE_TEMPLATES } from '../../data/challengeTemplates';
import { CURRENCIES, RECIPES, unitsOf, type Amounts, type Currency } from './statEconomy';

const INCOME_SCALE = Number(process.env.INCOME_SCALE ?? 1.2);
const SHORT: Record<Currency, string> = { power: 'P', quickness: 'Q', technique: 'T', mind: 'M' };

interface Site {
  source: 'story' | 'challenge';
  id: string;
  path: string;
  grant: Partial<Record<StatName, number>>;
}

/** Every object under `root` that has `key`, with the path to it. */
function findAll(root: unknown, key: string, path = ''): Array<{ path: string; value: unknown }> {
  if (typeof root !== 'object' || root === null) return [];
  const out: Array<{ path: string; value: unknown }> = [];
  for (const [k, v] of Object.entries(root as Record<string, unknown>)) {
    const p = Array.isArray(root) ? `${path}[${k}]` : path ? `${path}.${k}` : k;
    if (k === key && typeof v === 'object' && v !== null) out.push({ path: p, value: v });
    else out.push(...findAll(v, key, p));
  }
  return out;
}

function toCurrency(grant: Partial<Record<StatName, number>>): Amounts {
  const raw: Record<Currency, number> = { power: 0, quickness: 0, technique: 0, mind: 0 };
  for (const [stat, pts] of Object.entries(grant) as Array<[StatName, number]>) {
    if (pts <= 0) continue;
    for (const [c, n] of Object.entries(RECIPES[stat]) as Array<[Currency, number]>) {
      raw[c] += pts * n * INCOME_SCALE;
    }
  }
  const out: Amounts = {};
  for (const c of CURRENCIES) if (raw[c] > 0) out[c] = Math.max(1, Math.round(raw[c]));
  return out;
}

const fmtGrant = (g: Partial<Record<StatName, number>>): string =>
  Object.entries(g)
    .map(([k, v]) => `${k} ${v > 0 ? '+' : ''}${v}`)
    .join(', ');
const fmtAmounts = (a: Amounts): string =>
  CURRENCIES.filter((c) => a[c])
    .map((c) => `${a[c]} ${SHORT[c]}`)
    .join(' · ') || '—';

function main(): void {
  const sites: Site[] = [];
  for (const event of StoryEventRepository.getAllEvents()) {
    for (const { path, value } of findAll(event, 'statChanges')) {
      sites.push({ source: 'story', id: event.id, path, grant: value as Site['grant'] });
    }
  }
  for (const [id, template] of Object.entries(CHALLENGE_TEMPLATES)) {
    for (const { path, value } of findAll(template, 'statBoosts')) {
      sites.push({ source: 'challenge', id, path, grant: value as Site['grant'] });
    }
  }
  const withGrant = sites.filter((s) => Object.keys(s.grant).length > 0);
  const penalties = withGrant.filter((s) => Object.values(s.grant).some((v) => (v ?? 0) < 0));

  const totals = {
    points: 0,
    penaltyPoints: 0,
    currency: { power: 0, quickness: 0, technique: 0, mind: 0 },
  };
  for (const s of withGrant) {
    for (const v of Object.values(s.grant)) {
      if ((v ?? 0) > 0) totals.points += v ?? 0;
      else totals.penaltyPoints += -(v ?? 0);
    }
    const c = toCurrency(s.grant);
    for (const k of CURRENCIES) totals.currency[k] += c[k] ?? 0;
  }

  const out: string[] = [];
  out.push('# Content conversion — dry run');
  out.push('');
  out.push(
    `Generated by \`src/test/analysis/contentConversion.ts\` (INCOME_SCALE ${INCOME_SCALE}). ` +
      "Each positive stat grant is paid through its stat's recipe; no data has been changed. " +
      'Review this before the conversion is applied.',
  );
  out.push('');
  out.push('## Summary');
  out.push('');
  out.push(`| | sites | stat points granted | penalty points |`);
  out.push(`| --- | --- | --- | --- |`);
  for (const src of ['story', 'challenge'] as const) {
    const ss = withGrant.filter((s) => s.source === src);
    const pts = ss.reduce(
      (a, s) => a + Object.values(s.grant).reduce((b, v) => b + Math.max(0, v ?? 0), 0),
      0,
    );
    const pen = ss.reduce(
      (a, s) => a + Object.values(s.grant).reduce((b, v) => b + Math.max(0, -(v ?? 0)), 0),
      0,
    );
    out.push(`| ${src} | ${ss.length} | ${pts} | ${pen} |`);
  }
  out.push('');
  out.push(
    `Converted, all sites: ${fmtAmounts(totals.currency)} — ${unitsOf(totals.currency)} units for ` +
      `${totals.points} stat points (${(unitsOf(totals.currency) / totals.points).toFixed(2)} units a point).`,
  );
  out.push('');
  out.push('## Penalties (decision needed)');
  out.push('');
  out.push(
    `${penalties.length} sites lower a stat. There is no currency to take back without a respec, so ` +
      'the options are: keep them as direct stat changes (a stat can still go down), drop them, or ' +
      'turn them into a lost day of income. The positive part of each site converts as below either way.',
  );
  out.push('');
  out.push('| source | id | where | grant |');
  out.push('| --- | --- | --- | --- |');
  for (const s of penalties)
    out.push(`| ${s.source} | \`${s.id}\` | \`${s.path}\` | ${fmtGrant(s.grant)} |`);
  out.push('');
  out.push('## Every site');
  out.push('');
  out.push('| source | id | where | today | becomes |');
  out.push('| --- | --- | --- | --- | --- |');
  for (const s of withGrant) {
    out.push(
      `| ${s.source} | \`${s.id}\` | \`${s.path}\` | ${fmtGrant(s.grant)} | ${fmtAmounts(toCurrency(s.grant))} |`,
    );
  }
  console.log(out.join('\n'));
}

main();
